AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gifbot

  Returns GIF based on given search term

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Name: gifbot
    EndpointConfiguration: REGIONAL
  Function:
    Runtime: nodejs22.x
    Timeout: 3
    Tags:
      Application: bots
    Environment:
      Variables:
        companyId: '{{resolve:ssm:/Basecamp/CompanyID:1}}'
        giphyAPIKey: '{{resolve:ssm:/Giphy/APIKey:1}}'

Resources:
  GifBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: gifbot
      CodeUri: ./
      Handler: app.handler
      Description: Returns GIF based on given search term
      Events:
        GifBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
  GifBotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GifBotFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${GifBotFunction}
      RetentionInDays: 30

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # ServerlessRestApiProdStage is an implicit API stage created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GifBotApiEndpoint:
    Description: 'GifBot REST API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/'
  GifBotFunction:
    Description: 'GifBot Lambda Function ARN'
    Value: !GetAtt GifBotFunction.Arn
  GifBotFunctionIamRole:
    Description: 'Implicit IAM Role created for GifBot function'
    Value: !GetAtt GifBotFunctionRole.Arn
